# Generated by Django 4.2.1 on 2024-04-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='member_id',
        ),
        migrations.AddField(
            model_name='session',
            name='user_id',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
