# Generated by Django 4.2.1 on 2024-04-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_remove_session_member_id_session_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='token',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='user_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
