# Generated by Django 4.2.1 on 2024-04-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0003_alter_session_token_alter_session_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='access_type',
            field=models.CharField(default='normal', max_length=10),
        ),
    ]
