# Generated by Django 5.0.4 on 2024-04-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('part', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
