# Generated by Django 5.0.4 on 2024-04-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='grade',
            field=models.CharField(default='', max_length=50),
        ),
    ]
